# Generated by Django 4.x on 2026-02-24

from django.db import migrations, models
import django.db.models.deletion
import django.contrib.auth.models
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Members model
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_no', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('employee', 'Employee')], default='admin', max_length=50, blank=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),

        # Client (Tenant) model
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('auto_create_schema', models.BooleanField(default=True)),
                ('domain_url', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),

        # Domain model
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='yourapp.client')),
            ],
        ),

        # SetupCompany model
        migrations.CreateModel(
            name='SetupCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, default='')),
                ('address', models.TextField(max_length=90, null=True, default='')),
                ('phone', models.CharField(max_length=10, null=True, default='')),
                ('gst', models.CharField(max_length=15, null=True, default='')),
                ('bank', models.CharField(max_length=20, null=True, default='')),
                ('account', models.CharField(max_length=20, null=True, default='')),
                ('ifsc', models.CharField(max_length=15, null=True, default='')),
                ('due_date', models.CharField(max_length=5, null=True, default=0, help_text='Enter in days')),
                ('gsttype', models.CharField(choices=[('0','GST Exempted'),('5','5%'),('24','24%'),('18','18%')], default='Essential Goods', max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # Add_item_model_purch
        migrations.CreateModel(
            name='Add_item_model_purch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('rate', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),

        # Add_item_model_sale
        migrations.CreateModel(
            name='Add_item_model_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('rate', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),

        # Customer model
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, default='')),
                ('address', models.TextField(max_length=90, null=True, default='')),
                ('phone', models.CharField(max_length=10, null=True, default='')),
                ('gst', models.CharField(max_length=15, null=True, default='')),
                ('bank', models.CharField(max_length=20, null=True, default='')),
                ('account', models.CharField(max_length=20, null=True, default='')),
                ('ifsc', models.CharField(max_length=15, null=True, default='')),
                ('due_date', models.CharField(max_length=5, null=True, default=0, help_text='Enter in days')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # Seller model
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, default='')),
                ('address', models.TextField(max_length=90, null=True, default='')),
                ('phone', models.CharField(max_length=10, null=True, default='')),
                ('gst', models.CharField(max_length=15, null=True, default='')),
                ('bank', models.CharField(max_length=20, null=True, default='')),
                ('account', models.CharField(max_length=20, null=True, default='')),
                ('ifsc', models.CharField(max_length=15, null=True, default='')),
                ('due_date', models.CharField(max_length=5, null=True, default=0, help_text='Enter in days')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # Purchase_model
        migrations.CreateModel(
            name='Purchase_model',
            fields=[
                ('num', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Bill num')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date1', models.DateField(auto_now_add=True)),
                ('billnum', models.IntegerField(null=True, verbose_name='Bill Number')),
                ('mode', models.CharField(choices=[('cash','cash'),('Bank','Bank'),('credit','credit')], default='cash', max_length=15, blank=True, null=True, verbose_name='Mode')),
                ('qty', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Quantity')),
                ('rate', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Rate')),
                ('gst', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='GST')),
                ('amt', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Amt')),
                ('product', models.ForeignKey(default='name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Product1:+', to='yourapp.add_item_model_purch')),
                ('selbuy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.seller')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # Invoice_model
        migrations.CreateModel(
            name='Invoice_model',
            fields=[
                ('num', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Bill num')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date1', models.DateField(auto_now_add=True)),
                ('billnum', models.IntegerField(null=True, verbose_name='Bill Number')),
                ('mode', models.CharField(choices=[('cash','cash'),('Bank','Bank'),('credit','credit')], default='cash', max_length=15)),
                ('qty', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='quantity')),
                ('rate', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Rate')),
                ('gst', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='GST')),
                ('amt', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Amt')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='yourapp.add_item_model_sale', verbose_name='prod:')),
                ('selbuy', models.ForeignKey(null=False, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # CashBook
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date1', models.DateField(auto_now_add=True)),
                ('amt', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Amount Paid')),
                ('mode', models.CharField(choices=[('cash','cash'),('Bank','Bank')], default='cash', max_length=15)),
                ('comment', models.TextField(blank=True, choices=[('Advance Paid','Advance Paid'),('Balance Paid','Balance Paid'),('Full Payment','Full Payment'),('Cash in Hand','Cash in Hand'),('Bank Transfer','Bank Transfer'),('Other','Other')], max_length=150, null=True, verbose_name='narration')),
                ('selbuy', models.ForeignKey(null=False, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # PurchaseBook
        migrations.CreateModel(
            name='PurchaseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date1', models.DateField(auto_now_add=True)),
                ('amt', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Amount Paid')),
                ('mode', models.CharField(choices=[('cash','cash'),('Bank','Bank')], default='cash', max_length=15, verbose_name=' mode')),
                ('comment', models.TextField(blank=True, choices=[('Advance Paid','Advance Paid'),('Balance Paid','Balance Paid'),('Full Payment','Full Payment'),('Cash in Hand','Cash in Hand'),('Bank Transfer','Bank Transfer'),('Other','Other')], max_length=150, null=True, verbose_name='narration')),
                ('selbuy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.seller')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.members')),
            ],
        ),

        # Transportation
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date1', models.DateField(auto_now_add=True)),
                ('receipt_num', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('vehicle_no', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('date_supply', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('transporter_name', models.CharField(max_length=100, verbose_name='Transporter Name')),
                ('qty', models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Quantity')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.invoice_model')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yourapp.purchase_model')),
            ],
        ),
    ]
