# Generated by Django 5.1.8 on 2025-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_item_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
