# Generated by Django 5.2.8 on 2026-02-24 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoapp', '0009_purchase_model_id_alter_purchase_model_billnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchase_model',
            name='billnum',
            field=models.IntegerField(default=datetime.datetime(2026, 2, 24, 13, 2, 59, 512492, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='Bill Number'),
            preserve_default=False,
        ),
    ]
